# syntax = docker/dockerfile:1.4
# vim: syntax=dockerfile
FROM quay.io/rockylinux/rockylinux:10-minimal AS build


ARG CEPH_CLUSTER_VERSION
ARG CEPH_CLUSTER_CEPH_REPO_BASEURL
ARG CEPH_CLUSTER_EPEL_REPO_URL=""

ARG MICRODNF_OPTS="\
    --enablerepo crb \
    --nobest \
    --nodocs \
    --setopt=install_weak_deps=0 \
    --setopt=keepcache=1 \
    --setopt=cachedir=/var/cache/microdnf \
  "

ARG CEPH_PACKAGES="\
    ceph-common \
    ceph-mon \
    ceph-osd \
    ceph-mds \
    ceph-mgr \
    ceph-mgr-dashboard \
    ceph-radosgw \
    ceph-exporter \
    hostname \
    jq \
    net-tools \
    iproute \
    openssl \
    "
# TODO: To remove when ceph-mgr-dashboard defines these as deps
ARG EXTRA_PACKAGES="\
    python3-grpcio\ 
    python3-grpcio-tools \
    "
ARG DEBUG_PACKAGES="\
    procps-ng \
    strace \
    perf \
    ltrace \
    lsof \
    "

RUN <<EOF
    echo Log variables
    echo ======================================================================
    echo CEPH_CLUSTER_CEPH_REPO_BASEURL=$CEPH_CLUSTER_CEPH_REPO_BASEURL
    echo CEPH_CLUSTER_VERSION=$CEPH_CLUSTER_VERSION
    echo ======================================================================
EOF

COPY <<EOF /etc/yum.repos.d/ceph.repo
[Ceph]
name=Ceph packages for \$basearch
baseurl=${CEPH_CLUSTER_CEPH_REPO_BASEURL:-https://download.ceph.com/rpm-${CEPH_CLUSTER_VERSION}/el\$releasever}/\$basearch
enabled=1
priority=2
gpgcheck=0

[Ceph-noarch]
name=Ceph noarch packages
baseurl=${CEPH_CLUSTER_CEPH_REPO_BASEURL:-https://download.ceph.com/rpm-${CEPH_CLUSTER_VERSION}/el\$releasever}/noarch
enabled=1
priority=2
gpgcheck=0
EOF

RUN cat /etc/yum.repos.d/ceph.repo

RUN rpm -vih https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm
RUN if [ -n "$CEPH_CLUSTER_EPEL_REPO_URL" ]; then \
      curl -fL -o /etc/yum.repos.d/ceph-epel.repo "$CEPH_CLUSTER_EPEL_REPO_URL"; \
    fi

RUN microdnf install -y $MICRODNF_OPTS \
      $CEPH_PACKAGES \
      $EXTRA_PACKAGES \
      $DEBUG_PACKAGES


#------------------------------------------------------------------------------
FROM build

LABEL maintainer \
      ceph=True \
      RELEASE \
      GIT_REPO \
      GIT_BRANCH \
      GIT_COMMIT

ENV MON=1 \
    MGR=1 \
    OSD=3 \
    MDS=0 \
    FS=0 \
    RGW=0 \
    NFS=0 \
    CEPH_PORT=10000 \
    CEPH_VSTART_ARGS="--bluestore --without-dashboard"

ENV CEPH_BIN=/usr/bin \
    CEPH_LIB=/usr/lib64/ceph \
    CEPH_CONF_PATH=/etc/ceph \
    EC_PATH=/usr/lib64/ceph/erasure-code \
    OBJCLASS_PATH=/usr/lib64/rados-classes \
    MGR_PYTHON_PATH=/usr/share/ceph/mgr \
    PYBIND=/usr/share/ceph/mgr

VOLUME $CEPH_CONF_PATH
RUN chown ceph:ceph $CEPH_CONF_PATH

RUN ln -sf $EC_PATH/* $CEPH_LIB && \
    ln -sf $OBJCLASS_PATH/* $CEPH_LIB && \
    ln -sf $CEPH_LIB/compressor/* $CEPH_LIB

USER ceph
WORKDIR /ceph
ADD --chown=ceph:ceph --chmod=755 \
    https://raw.githubusercontent.com/ceph/ceph/v${CEPH_CLUSTER_VERSION:?}/src/vstart.sh .

COPY <<EOF ./CMakeCache.txt
ceph_SOURCE_DIR:STATIC=/ceph
WITH_MGR_DASHBOARD_FRONTEND:BOOL=ON
WITH_RBD:BOOL=ON
EOF

ENTRYPOINT \
    ./vstart.sh --new $CEPH_VSTART_ARGS && \
    sleep infinity
