FROM golang:1.24

ENV MODULE=github.com/ceph/ceph-nvmeof/lib/go/nvmeof

# install tools
RUN true \
	&& apt-get update \
	&& apt install -y protobuf-compiler \
	&& go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
	&& go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest \
	&& true
