
ARG spdk_version

FROM spdk:${spdk_version:-latest} as spdk

FROM fedora:33 AS base

COPY --from=spdk /tmp/rpms/*.rpm /tmp/


RUN dnf update -y \
    && dnf install -y libaio numactl-libs python3-pip \
    && pip3 --no-cache-dir install --upgrade pip \
    && python3 -m pip install grpcio \
    && python3 -m pip install grpcio-tools

COPY docker/post-install /tmp/post-install

RUN /tmp/post-install

COPY . /app/

RUN rm -rf /app/spdk

CMD ["/bin/bash"]

