# Blocks PR merging if PR description contains "depends on" or "blocked by"
# pointing to another PR until that PR is merged

name: Check Dependencies
on: [pull_request]

jobs:
  check-deps:
    runs-on: ubuntu-latest
    name: Check Dependencies
    steps:
    # https://github.com/marketplace/actions/pr-dependency-check
    # Pinned for security reasons
    # Approved Github Actions: https://github.com/orgs/ceph/projects/11/views/1
    - uses: gregsdennis/dependencies-action@f98d55eee1f66e7aaea4a60e71892736ae2548c7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
